Mobile-first: Milestone 3
saluumaa/Saluma-s-Portfolio pull request #4
Opened 2023-01-17 14:00 UTC by saluumaa

In this part I:
1. Added a contact section in the Html file
2. Added a style in the contact section using CSS
3. check the errors using linters

2023-01-17 14:07 UTC, amejid reviewed
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that does not have a README file following the provided template. Kindly update your README file using [the template](https://github.com/microverseinc/readme-template) provided by Microverse.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-17 16:50 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @saluumaa , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

You did an exceptional job but there are some issues in the styling which need to be addressed to go to the next level.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

 ## Required Changes ♻️

**_Check the comments below to see the changes required._**


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 16:50 UTC, ABDULALI3468 commented on style.css
> +}
Your style is not exactly similar to the [Figma Template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=8P269HoVLs4fzLYn-0). Your width is `375px` where in the template it `is 327px` with the center aligned. Please consider reviewing your styles to make them exact replica of the template so it looks more better and perfect.

2023-01-17 16:50 UTC, ABDULALI3468 commented on style.css
> +}
Please consider reviewing your fonts in accordance with the template fonts. The font family used in the Figma template is `    font-family: 'Poppins';` They might not be available generally so you can download or use the CDN link of Google fonts for them to use.

2023-01-17 16:50 UTC, ABDULALI3468 commented on style.css
>    background-color: #fff;
Please consider reviewing your styles. Try using the following syntax to achieve that the pressed functionality:-

`.btn:active{
  color: #FFFFFF;
  background: #2230D2;
}`

2023-01-18 05:55 UTC, PinkMoon25 approved these changes
Hi @saluumaa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
linter checks :heavy_check_mark: 
form implementation :heavy_check_mark: 
HTML validation :heavy_check_mark: 

## Optional suggestions

**- [ ] Please add a license file to your project and fix the MIT link in the readem which currently id giving a 404 error**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 05:59 UTC, merged